- hosts: all
  tasks: 
       - name: Creating a docker repository
         yum_repository:
                 description: "repository  for docker"
                 name: "docker"
                 baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
                 gpgcheck: false
       - name: install docker
         package: 
                 name: "docker-ce-18.09.1-3.el7.x86_64"
                 state: present

       - name: Starting docker services
         service: 
                name: docker
                state: started

       - pip: 
               name: docker-py
       - name: pulling docker image
         docker_image:
                 name: httpd
                 source: pull
       - name: copying file to managed node
         copy: 
                 src: /root/ansible_ws/web.html
                 dest: /home
       - name: creating a docker container for the webserver
         community.general.docker_container:
                 name: webserver
                 image: httpd
                 ports: 
                     - "8080:80"
                 state: started
                 detach: yes
                 volumes: /home/:/usr/local/apache2/htdocs/ 
                   
